name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish new version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Publish to pub.dev
        run: |
          echo ${{ secrets.PUB_CREDENTIALS }} > ~/.pub-cache/credentials.json
          dart pub publish -f
